# Generated by Django 2.0.4 on 2018-04-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.URLField(verbose_name='产品链接')),
                ('digest', models.CharField(max_length=200, verbose_name='一句话描述')),
                ('vote_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('public', models.BooleanField(default=True, verbose_name='上线?')),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '产品点赞',
                'verbose_name_plural': '产品点赞',
                'db_table': 'product_vote',
            },
        ),
    ]
