# Generated by Django 2.0.4 on 2018-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='产品ID'),
        ),
    ]
