# Generated by Django 2.0.4 on 2018-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(default='http://sdn.haimaxy.com/icon/haimaxy-wx-logo.png', max_length=500, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='用户ID'),
        ),
    ]
